name: flutter_silero_vad_example
description: Demonstrates how to use the flutter_silero_vad plugin.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  audio_session: ^0.1.21
  audio_streamer:
    git:
      url: https://github.com/0235-jp/audio_streamer.git
      ref: 0235-jp
  audioplayers: ^6.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_silero_vad:
    path: ../
  hooks_riverpod: ^2.6.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1


dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/silero_vad.v5.onnx
